import { CTA } from '@/components/cta';
import { Icon } from '@/components/icon';
import { PageHero } from '@/components/page-hero';
import { Reveal } from '@/components/reveal';

export const metadata = { title: 'Food Safety' };

export default function FoodSafety(){return <>
<PageHero eyebrow="FOOD SAFETY" title="Make food-safety controls part of the work—not a separate paperwork exercise." text="Digitize recurring checks, temperature controls, receiving inspections, sanitation, corrective actions, SOP access and audit evidence across every location.">
  <div className="mini-console"><div className="mini-console-head"><strong>Food safety control centre</strong><span>Live</span></div><div className="mini-console-grid"><div className="mini-console-card"><span>Hygiene checks</span><strong>On track</strong></div><div className="mini-console-card"><span>Temperature logs</span><strong>Live</strong></div><div className="mini-console-card"><span>Open findings</span><strong>4</strong></div><div className="mini-console-card"><span>Evidence</span><strong>Linked</strong></div></div></div>
</PageHero>
<section className="content-section"><div className="shell content-grid"><Reveal><div><span className="eyebrow">DAILY EXECUTION</span><h2>From HACCP-related controls to everyday hygiene routines.</h2><p>InCheck 360 helps teams execute and document operational controls such as receiving, storage, cooking, cooling, cleaning, personal hygiene and temperature verification. The platform supports the execution and evidence around a food-safety management system; it does not replace certification or regulatory requirements.</p><div className="bullet-grid">{['Receiving inspections','Temperature checks','Cleaning & sanitation','Personal hygiene','Storage controls','Corrective actions','Evidence capture','Audit trails'].map(x=><div className="bullet-item" key={x}><span>✓</span>{x}</div>)}</div></div></Reveal><Reveal><div className="content-panel"><span className="eyebrow">FOOD SAFETY WORKFLOW</span>{[['01','Check','Complete the right control at the right time.'],['02','Flag','Capture failures, out-of-range values or evidence.'],['03','Correct','Assign the corrective action and owner.'],['04','Verify','Confirm closure and preserve the record.']].map(x=><div className="simple-card" style={{marginTop:10}} key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></Reveal></div></section>
<section className="content-section" style={{background:'#f5f9fd'}}><div className="shell"><span className="eyebrow">SUPPORTING HACCP & ISO 22000 OPERATIONS</span><h2 style={{maxWidth:760,fontFamily:'var(--font-manrope)',fontSize:48,letterSpacing:'-.04em'}}>Digital evidence around the controls your system already requires.</h2><div className="simple-card-grid" style={{marginTop:35}}>{[['Structured controls','Turn recurring operational controls into scheduled digital workflows.'],['Traceable evidence','Keep responses, photos, timestamps and action history connected to the record.'],['Management visibility','Review trends, open findings and location performance centrally.']].map(([t,p],i)=><div className="simple-card" key={t}><Icon name={i===0?'check':i===1?'camera':'chart'}/><h3>{t}</h3><p>{p}</p></div>)}</div></div></section><CTA/></>}
