export const clientLogos = [
  { name: 'Advanced Food Co.', src: '/clients/advanced-food.jpeg' },
  { name: 'Angelina Paris', src: '/clients/angelina-paris.png' },
  { name: 'BAB Mansour', src: '/clients/bab-mansour.png' },
  { name: 'Bachir Ice Cream', src: '/clients/bachir-ice-cream.png' },
  { name: 'Beirut Khanum', src: '/clients/beirut-khanum.png' },
  { name: 'Beit Wared', src: '/clients/beit-wared.png' },
  { name: 'Black Spoon', src: '/clients/black-spoon.png' },
  { name: 'Boubess Group', src: '/clients/boubess-group.png' },
  { name: 'Box For Less', src: '/clients/box-for-less.jpeg' },
  { name: 'Bunny', src: '/clients/bunny.png' },
  { name: 'Butcheria', src: '/clients/butcheria.png' },
  { name: 'Cafe Centreville', src: '/clients/cafe-centreville.png' },
  { name: 'Faddoul', src: '/clients/faddoul.png' },
  { name: "Global's F&B House", src: '/clients/globals-fb-house.jpeg' },
  { name: 'Ibn Al Bahr', src: '/clients/ibn-al-bahr.png' },
  { name: 'Immersive Xperiences', src: '/clients/immersive-xperiences.png' },
  { name: 'Kcal', src: '/clients/kcal.png' },
  { name: "Le Relais de l'Entrecôte", src: '/clients/le-relais-de-lentrecote.png' },
  { name: 'Lebanese Roaster', src: '/clients/lebanese-roaster.png' },
  { name: 'Maison Dada', src: '/clients/maison-dada.png' },
  { name: 'Maître Choux', src: '/clients/maitre-choux.jpeg' },
  { name: "Mama'esh", src: '/clients/mamaesh.png' },
  { name: 'Maryool', src: '/clients/maryool.png' },
  { name: 'Meat the Fish', src: '/clients/meat-the-fish.jpeg' },
  { name: 'MET Brasserie Métropolitaine', src: '/clients/met-brasserie-metropolitaine.png' },
  { name: 'Métropole Brasserie', src: '/clients/metropole-brasserie.png' },
  { name: 'MRKT Beirut Souks', src: '/clients/mrkt-beirut-souks.png' },
  { name: 'Pizzeria Napoletana', src: '/clients/pizzeria-napoletana.png' },
  { name: 'Shababeek', src: '/clients/shababeek.jpeg' },
  { name: 'Sibon', src: '/clients/sibon.png' },
  { name: 'Skirt', src: '/clients/skirt.png' },
  { name: 'Soul Kitchen', src: '/clients/soul-kitchen.png' },
  { name: 'The Chain', src: '/clients/the-chain.png' },
  { name: 'Tre Saj', src: '/clients/tre-saj.png' },
  { name: 'WatchHouse', src: '/clients/watchhouse.png' },
  { name: 'Yummy Junction', src: '/clients/yummy-junction.jfif' },
  { name: 'Zahret Lebnan', src: '/clients/zahret-lebanan.png' },
] as const;
